modLoader = "javafml"
loaderVersion = "[4,)"
license = "All Rights Reserved"

[[mods]]
modId = "armory_rpgs"
version = "${version}"
displayName = "Armory (RPG Series)"
authors = "Daedelus"
description = '''
Epic armor sets, with unique designs and set bonuses.
'''
logoFile = "icon.png"

[[dependencies.armory_rpgs]]
modId = "neoforge"
type = "required"
versionRange = "[21.11,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.armory_rpgs]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.11,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.armory_rpgs]]
modId = "spell_engine"
type = "required"
versionRange = "[${spell_engine_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.armory_rpgs]]
modId = "ranged_weapon_api"
type = "required"
versionRange = "[${ranged_weapon_api_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.armory_rpgs]]
modId = "armor_model_api"
type = "required"
versionRange = "[${armor_model_api_version},)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "armory_rpgs.mixins.json"
